export const GET_AVAILABLE_TURNS = 'GET_AVAILABLE_TURNS';
export const GET_LEVEL = 'GET_LEVEL';
export const UPDATED_CONFIGURATION = 'UPDATED_CONFIGURATION';
export const DECREASE_AVAILABLE_TURNS = 'DECREASE_AVAILABLE_TURNS';
